name: GitHub Actions Demo
on: [push]
permissions:
  actions: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Show files changed
        # run: cat $HOME/work/privat/privat/Quellcode/code.c
        run: cat ${{ github.workspace }}/Quellcode/code.c
      - run: echo "Hello World" > ${{ github.workspace }}/Quellcode/hello.c
      - run: echo "🍏 This job's status is ${{ job.status }}."
      # Commit and add.
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: 'Your commit message'
          add: '*.c'
      # Commit and push all changed files.
      #- name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      # Only run on main branch push (e.g. after pull request merge).
      #  if: github.event_name == 'push'
      #  run: |
      #    git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
      #    git config --global user.email "username@users.noreply.github.com"
      #    git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
      #    git push
