name: GitHub Actions Demo
on: [push]
permissions:
  actions: write
  pull-requests: write
  issues: write
  repository-projects: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Use variables
        run: |
          echo "repository variable : ${{ vars.REPLOG }}"
          echo "variable from shell environment : ${{ github.ref }}"
          echo "variable from shell environment : ${{ github.RUNNER_NAME }}"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Show files changed
        # run: cat $HOME/work/privat/privat/Quellcode/code.c
        run: cat ${{ github.workspace }}/Quellcode/code.c
      #- run: echo "Hello World" > ${{ github.workspace }}/Quellcode/hello.txt
      - run: echo "Hello World" > ${{ github.workspace }}/hello.c
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
      - name: List files in the repository2
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      # Commit and add.
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: Your Name
          author_email: mail@example.com
          message: 'Your commit message'
          add: '*.c'
      #Issues
      #- name: Issues    
      #  run: |
      #    curl --request POST \
      #    --url https://api.github.com/repos/${{ github.repository }}/issues \
      #    --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #    --header 'content-type: application/json' \
      #    --data '{
      #      "title": "Automated issue for commit: ${{ github.sha }}",
      #      "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
      #      }' \
      #    --fail
      
